#! /usr/bin/bash
DST=`pwd`
SRC="/home/hendrik/Desktop/PHP\ START/php-oop-mvc-bashbot/"
echo ...
echo ...
echo Executing Hyper Woke Paradigm Shift
echo ...
echo ...
echo ...
echo Bashbot will now copy the template from $SRC to $DST
read -p "Is this acceptable? (Y/N):" ANSWER



